spring:
  application:
    name: fo-api

  datasource:
    url: jdbc:mysql://localhost:3306/stylink?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

server:
  port: 8080

logging:
  level:
    com.stylink: DEBUG
    org.hibernate.SQL: DEBUG
